name: CI testing

on:
  pull_request:
    branches: [ develop ]
    paths-ignore:
      - '**/README.md'
      - 'docs/**'

  workflow_dispatch:

jobs:
  ci:
    if: github.actor == 'sluggish-yard'
    runs-on: ubuntu-20.04
    continue-on-error: false

    strategy:
      matrix:
        python: ["3.7", "3.8", "3.9"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Upgrade pip
        run: pip install --upgrade pip pipenv

      - name: Install pipenv
        run: pipenv install --dev --skip-lock --python ${{ matrix.python }}

      - name: Run make ci
        run: make ci
