# .github/workflows/pypi-publish.yml
name: Publish to PyPI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - 'Pipfile.lock'

jobs:
  build-n-publish:
    if: github.actor != 'dependabot-preview[bot]'
    name: Build Python distribution and publish to PyPI
    runs-on: ubuntu-latest
    steps:
      # https://github.com/pypa/gh-action-pypi-publish
      # https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Upgrade pip
        run: python -m pip install --upgrade pipenv

      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user

      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/

      # Only runs on tagged pushes.
      - name: Publish distribution to PyPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}